### ISSUE TITLE
RFC: flatpak package

### ISSUE THREAD

**Issue by Barthalion** [OpenOrienteering/mapper#984]
Sometime ago Mapper has been mentioned on Fedora's mailing list as package request. As there is no point in duplicating effort across distributions, I prepared a simple manifest for Flatpak [here](https://github.com/flathub/flathub/pull/105).

Now, as I'm not using Mapper myself, I'd love to get some feedback from you – is there anything that should be changed from your point of view? Would you be willing to (co-)maintain it with me? After standalone repository is created, every commit is automatically build so it's rather straightforward to provide new releases to Linux users.

**Comment by dg0yt** [comment]
Duplicate of #894

**Comment by dg0yt** [comment]
Such packages can only be published when they satisfy the licensing requirements of all software included in this package. See 894 for comments I made for an AppImage recipe.

OTOH we do provide Fedora packages, build from a regular spec file in a regular Fedora environment.

**Comment by rugk** [comment]
see also: https://github.com/OpenOrienteering/mapper/issues/894#issuecomment-532082192

**Comment by mfbehrens** [comment]
I created a flatpak definition that builds all the dependencies. The only thing that fails is building oomapper since it is not able to download polyclipping (which has already been built) from sourceforge (Download still works, maybe flatpak sandboxes installation process).

Maybe somebody can help?

```
app-id: org.openorienteering.Mapper
runtime: org.kde.Platform
runtime-version: "5.15-22.08"
sdk: org.kde.Sdk
command: openorienteeringmapper
finish-args:
  - --share=ipc
  - --share=network
  - --filesystem=home
  - --device=dri

modules:
  # # OpenOrienteering Mapper superbuild
  # # Did not work :(
  # - name: oomapper
  #   buildsystem: cmake
  #   sources:
  #     - type: git
  #       url: https://github.com/OpenOrienteering/superbuild.git
  #       tag: v20210109
  #       commit: "ecb23f9b23c26ac8f629dcb0e65211b59699d80f"

  # Build OpenOrienteering Mapper
  - name: oomapper
    buildsystem: cmake
    config-opts:
      - -DLICENSING_PROVIDER=
      - -DCMAKE_INSTALL_PREFIX=/app
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DMapper_BUILD_CLIPPER=ON
      - -DGDAL_ROOT_DIR=/app
      - -DPROJ_ROOT=/app
      - -DZLIB_ROOT=/app
      - -DQt5_DIR=/app/lib/cmake/Qt5
      - -Wno-dev
    sources:
      - type: git
        url: https://github.com/OpenOrienteering/mapper.git
        tag: v0.9.5
        commit: "5fc6056de1165476c1c472fbc54e0070fbff046c"
    modules:
    # PROJ for cartographic projections
    - name: proj
      buildsystem: cmake
      config-opts:
        - -DCMAKE_INSTALL_PREFIX=/app
      sources:
        - type: archive
          url: https://download.osgeo.org/proj/proj-9.6.0.tar.gz
          md5: f6275f374409cb22efe25c5bc4e29459

    # SQLite geo database
    - name: sqlite3
      buildsystem: simple
      build-commands:
        - "CFLAGS='-O2 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_ICU' CPPFLAGS=`icu-config --cppflags` LDFLAGS=`icu-config --ldflags` ./configure --disable-static --enable-rtree --prefix=/app && make && make install"
      sources:
        - type: archive
          url: https://www.sqlite.org/2025/sqlite-autoconf-3490100.tar.gz
          sha256: 106642d8ccb36c5f7323b64e4152e9b719f7c0215acf5bfeac3d5e7f97b59254

    # GDAL for geospatial support
    - name: libgdal
      buildsystem: cmake
      # config-opts:
      #   - --with-python=no
      #   - --without-lua
      #   - --prefix=/app
      sources:
        - type: archive
          url: https://download.osgeo.org/gdal/3.10.3/gdal-3.10.3.tar.xz
          sha256: 335a8d2c7567d783563d3fed37e8b58d72d9c1723f6fd1d8c299fe4c0d936781

    # Clipper library
    - name: libpolyclipping
      buildsystem: cmake
      # config-opts:
      #   - -DCMAKE_INSTALL_PREFIX=/app
      sources:
        - type: archive
          url: https://sourceforge.net/projects/polyclipping/files/latest/download
          dest-filename: clipper_ver6.4.2.zip
          sha256: a14320d82194807c4480ce59c98aa71cd4175a5156645c4e2b3edd330b930627
```

Error:

```
[ 34%] Built target cove
-- Using src='http://sourceforge.net/projects/polyclipping/files/clipper_ver6.4.2.zip/download'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='http://sourceforge.net/projects/polyclipping/files/clipper_ver6.4.2.zip/download'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='http://sourceforge.net/projects/polyclipping/files/clipper_ver6.4.2.zip/download'
CMake Error at Clipper-stamp/download-Clipper.cmake:162 (message):
  Each download failed!

    error: downloading 'http://sourceforge.net/projects/polyclipping/files/clipper_ver6.4.2.zip/download' failed
          status_code: 6
          status_string: "Couldn't resolve host name"
          log:
          --- LOG BEGIN ---
          timeout on name lookup is not supported

  getaddrinfo(3) failed for sourceforge.net:80

  Could not resolve host: sourceforge.net

  Closing connection
```

**Comment by dg0yt** [comment]
Your script has:
~~~
      - -DMapper_BUILD_CLIPPER=ON
~~~
so you ask Mapper to build the lib. Use `OFF` ton enforce using an external copy.

**Comment by mfbehrens** [comment]
I am so stupid:

```yaml
app-id: org.openorienteering.Mapper
runtime: org.kde.Platform
runtime-version: "5.15-22.08"
sdk: org.kde.Sdk
command: Mapper
finish-args:
  - --socket=x11
  - --socket=wayland
  - --share=ipc
  - --share=network
  - --filesystem=home
  - --device=dri

modules:
  # Build OpenOrienteering Mapper
  - name: oomapper
    buildsystem: cmake
    config-opts:
      - -DLICENSING_PROVIDER=
      # - -DCMAKE_INSTALL_PREFIX=/app
      # - -DGDAL_ROOT_DIR=/app
      # - -DPROJ_ROOT=/app
      # - -DZLIB_ROOT=/app
      # - -DQt5_DIR=/app/lib/cmake/Qt5
      - -Wno-dev
    sources:
      - type: git
        url: https://github.com/OpenOrienteering/mapper.git
        tag: v0.9.5
        commit: "5fc6056de1165476c1c472fbc54e0070fbff046c"
    modules:
    - name: proj
      buildsystem: cmake
      config-opts:
        - -DCMAKE_INSTALL_PREFIX=/app
      sources:
        - type: archive
          url: https://download.osgeo.org/proj/proj-9.6.0.tar.gz
          md5: f6275f374409cb22efe25c5bc4e29459

    - name: sqlite3
      buildsystem: simple
      build-commands:
        - "CFLAGS='-O2 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_ICU' CPPFLAGS=`icu-config --cppflags` LDFLAGS=`icu-config --ldflags` ./configure --disable-static --enable-rtree --prefix=/app && make && make install"
      sources:
        - type: archive
          url: https://www.sqlite.org/2025/sqlite-autoconf-3490100.tar.gz
          sha256: 106642d8ccb36c5f7323b64e4152e9b719f7c0215acf5bfeac3d5e7f97b59254

    - name: libgdal
      buildsystem: cmake
      sources:
        - type: archive
          url: https://download.osgeo.org/gdal/3.10.3/gdal-3.10.3.tar.xz
          sha256: 335a8d2c7567d783563d3fed37e8b58d72d9c1723f6fd1d8c299fe4c0d936781

    - name: libpolyclipping
      buildsystem: cmake
      sources:
        - type: archive
          url: https://sourceforge.net/projects/polyclipping/files/latest/download
          dest-filename: clipper_ver6.4.2.zip
          sha256: a14320d82194807c4480ce59c98aa71cd4175a5156645c4e2b3edd330b930627
```

This works. Todos remain:
- [ ] Include icon
- [ ] Check if any cleanup is needed
- [ ] Check if everything works
